apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress
type: Opaque

stringData:
  root-password: "RootPassword123!"
  database: "wordpress"
  username: "wordpress"
  password: "WordpressPassword123!"
