apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: longhorn-single

  resources:
    requests:
      storage: 10Gi
